### PR TITLE
Add support for GPID

### PR DESCRIPTION
**Pull request by epechuzal**
https://sharethrough.atlassian.net/browse/PGE-178206245

### CODE REVIEW

**Review by maphe — COMMENTED** [review]
I'd suggest the GPID should be added to the request body rather than the query params, but not really a blocker since we're going to revamp the whole adapter to connect to the universal endpoint anyway.

Also if we're using `ExtImpSharethrough` that means our prebid config supports a new custom param, meaning we have to update the bidder documentation. Although just a heads up, it doesn't match what has been implemented on the Prebid.js side.

**Comment by epechuzal** [comment]
> I'd suggest the GPID should be added to the request body rather than the query params, but not really a blocker since we're going to revamp the whole adapter to connect to the universal endpoint anyway.
> 
> Also if we're using `ExtImpSharethrough` that means our prebid config supports a new custom param, meaning we have to update the bidder documentation. Although just a heads up, it doesn't match what has been implemented on the Prebid.js side.

I've been digging into

**Comment by epechuzal** [comment]
> I'd suggest the GPID should be added to the request body rather than the query params, but not really a blocker since we're going to revamp the whole adapter to connect to the universal endpoint anyway.
> 
> Also if we're using `ExtImpSharethrough` that means our prebid config supports a new custom param, meaning we have to update the bidder documentation. Although just a heads up, it doesn't match what has been implemented on the Prebid.js side.

Based on prebid docs I think we have the right location: https://docs.prebid.org/features/pbAdSlot.html

I don't see any mention of needing additional documentation, and as far as I can tell no other bidders added documentation for updating their `ExtImp` objects.

For the query vs request body I figured that when we use universal endpoint we would change it, but since right now everything is sent as a query param I kept the implementation similar to pbjs

**Review by maphe — APPROVED** [review]
> right now everything is sent as a query param
not really, the latest params that we added support for are in the body, but still doesn't matter much with universal id coming

Also according to the doc, it looks like we don't fetch gpid from the right location in PBJS :(

**Comment by epechuzal** [comment]
> > right now everything is sent as a query param
> > not really, the latest params that we added support for are in the body, but still doesn't matter much with universal id coming
> 
> Also according to the doc, it looks like we don't fetch gpid from the right location in PBJS :(

In pbjs the equivalent to prebid-server's `imp[].ext` object is captured in `ortb2Imp.ext`

I don't know why they have done it this way though 🤷

**Pull request closed without merging**
